nodes:
  - address: 10.142.0.12               # Change with the Private Ip of rancher server
    internal_address: 10.142.0.12      # Change with the Private Ip of rancher server
    user: zeus
    role:
      - controlplane
      - etcd
      - worker

# ignore_docker_version: true

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

ssh_key_path: ~/.ssh/petclinic-rancher.pem

# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"